const { PrismaClient } = require("@prisma/client");
const { PrismaBetterSqlite3 } = require("@prisma/adapter-better-sqlite3");

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" });
const prisma = new PrismaClient({ adapter });

const products = [
  {
    name: "iPhone 15 Pro Max Luxury Leather Case",
    description: "Premium genuine leather case for iPhone 15 Pro Max. Features MagSafe compatibility, raised camera protection, and elegant stitching.",
    price: 2499,
    originalPrice: 3500,
    category: "cases",
    brand: "DollarHub Premium",
    stock: 50,
    images: JSON.stringify(["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&q=80"]),
    rating: 4.8,
    reviewCount: 124,
    featured: true,
    badge: "Hot",
  },
  {
    name: "iPhone 14/15 Crystal Clear Magsafe Case",
    description: "Crystal clear case with built-in MagSafe magnets. Military-grade drop protection with anti-yellowing technology.",
    price: 899,
    originalPrice: 1299,
    category: "cases",
    brand: "ClearShield",
    stock: 120,
    images: JSON.stringify(["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&q=80"]),
    rating: 4.6,
    reviewCount: 89,
    featured: true,
    badge: "Sale",
  },
  {
    name: "Apple 20W USB-C Fast Charger",
    description: "Original Apple 20W USB-C power adapter. Supports fast charging for iPhone 8 and later. Compact design for travel.",
    price: 1999,
    originalPrice: null,
    category: "chargers",
    brand: "Apple",
    stock: 75,
    images: JSON.stringify(["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&q=80"]),
    rating: 4.9,
    reviewCount: 203,
    featured: true,
    badge: null,
  },
  {
    name: "45W GaN Fast Charger USB-C",
    description: "Ultra-compact 45W GaN charger. Charges iPhone 15 Pro from 0 to 50% in 30 minutes. Supports PD 3.0.",
    price: 2799,
    originalPrice: 3999,
    category: "chargers",
    brand: "Anker",
    stock: 40,
    images: JSON.stringify(["https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80"]),
    rating: 4.7,
    reviewCount: 156,
    featured: true,
    badge: "New",
  },
  {
    name: "9H Tempered Glass Screen Guard iPhone 15",
    description: "9H hardness tempered glass screen protector. Ultra-thin 0.33mm with oleophobic coating. 99.9% clarity.",
    price: 499,
    originalPrice: 799,
    category: "screen-guards",
    brand: "ShieldPro",
    stock: 200,
    images: JSON.stringify(["https://images.unsplash.com/photo-1601972602237-974592a893cf?w=400&q=80"]),
    rating: 4.5,
    reviewCount: 312,
    featured: true,
    badge: "Sale",
  },
  {
    name: "Anti-Spy Privacy Screen Guard iPhone 14/15",
    description: "Privacy screen protector. Blocks side view at 30°. HD clarity from straight on. Includes installation kit.",
    price: 749,
    originalPrice: null,
    category: "screen-guards",
    brand: "PrivacyShield",
    stock: 80,
    images: JSON.stringify(["https://images.unsplash.com/photo-1601972602237-974592a893cf?w=400&q=80"]),
    rating: 4.4,
    reviewCount: 67,
    featured: false,
    badge: null,
  },
  {
    name: "Premium Wireless Earbuds ANC",
    description: "Wireless earbuds with active noise cancellation. 30 hours total battery. IPX4 water resistance. Seamless iPhone pairing.",
    price: 8999,
    originalPrice: 12000,
    category: "earphones",
    brand: "ProSound",
    stock: 25,
    images: JSON.stringify(["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&q=80"]),
    rating: 4.8,
    reviewCount: 445,
    featured: true,
    badge: "Hot",
  },
  {
    name: "Lightning to USB-C Braided Cable 2M",
    description: "Heavy-duty braided Lightning cable. 2 meter length. Supports 20W fast charging. MFi certified.",
    price: 799,
    originalPrice: 1200,
    category: "cables",
    brand: "DollarHub",
    stock: 150,
    images: JSON.stringify(["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80"]),
    rating: 4.3,
    reviewCount: 98,
    featured: false,
    badge: "Sale",
  },
  {
    name: "20000mAh Power Bank 22.5W Fast Charge",
    description: "20000mAh power bank. Charges iPhone 15 Pro 4+ times. LED display. Dual USB-A + USB-C ports.",
    price: 3999,
    originalPrice: 5500,
    category: "power-banks",
    brand: "Baseus",
    stock: 35,
    images: JSON.stringify(["https://images.unsplash.com/photo-1609592862139-7e89cf41d9e7?w=400&q=80"]),
    rating: 4.6,
    reviewCount: 178,
    featured: true,
    badge: "Sale",
  },
  {
    name: "iPhone Magnetic Ring Holder Stand",
    description: "360° rotating magnetic ring holder. Works as desk stand or car mount. Slim and lightweight.",
    price: 599,
    originalPrice: null,
    category: "accessories",
    brand: "MagGrip",
    stock: 90,
    images: JSON.stringify(["https://images.unsplash.com/photo-1618424181497-157f25b6ddd5?w=400&q=80"]),
    rating: 4.2,
    reviewCount: 54,
    featured: false,
    badge: "New",
  },
  {
    name: "MagSafe Wireless Charger 15W",
    description: "MagSafe compatible 15W wireless charger. Perfectly aligns with iPhone 12-15 series. Includes USB-C cable.",
    price: 2299,
    originalPrice: 3000,
    category: "chargers",
    brand: "MagCharge",
    stock: 60,
    images: JSON.stringify(["https://images.unsplash.com/photo-1618044733300-9472054094ee?w=400&q=80"]),
    rating: 4.7,
    reviewCount: 234,
    featured: true,
    badge: null,
  },
  {
    name: "iPhone 15 Pro Titanium Frame Case",
    description: "Precision-machined aluminum alloy frame case. Matches iPhone 15 Pro titanium finish. Ultra-thin profile.",
    price: 3499,
    originalPrice: 4500,
    category: "cases",
    brand: "MetalGuard",
    stock: 20,
    images: JSON.stringify(["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&q=80"]),
    rating: 4.9,
    reviewCount: 41,
    featured: false,
    badge: "New",
  },
];

async function main() {
  console.log("Seeding database...");
  await prisma.product.deleteMany();
  for (const product of products) {
    await prisma.product.create({ data: product });
  }
  console.log(`✓ Created ${products.length} products successfully!`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
